// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import { cleanup, fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { type AggregatedTaskUsage } from "../lib/tokeiUsage";
import { copyCustomTaskCard } from "../lib/customTaskCard";
import { CustomTaskStatistics } from "./CustomTaskStatistics";
vi.mock("../lib/customTaskCard", () => ({ copyCustomTaskCard: vi.fn(), prepareCustomTaskCardFont: vi.fn().mockResolvedValue(undefined) }));
afterEach(cleanup);
const row = (id: string, cost: number | null, known?: number): AggregatedTaskUsage => {
  const metrics = { inputTokens: 100, cachedInputTokens: 0, outputTokens: 20, reasoningTokens: 0, totalTokens: 120, estimatedCostUsd: cost };
  return { ...metrics, knownCostUsd: known, id, name: id, rawName: id, relation: "root", children: [], self: { ...metrics, id, name: id, relation: "root", models: [] } };
};
const pointer = (element: Element, type: string, pointerId: number, clientX: number, clientY: number, pointerType = "mouse") => {
  const event = new MouseEvent(type, { bubbles: true, button: 0, clientX, clientY });
  Object.defineProperties(event, { pointerId: { value: pointerId }, pointerType: { value: pointerType } });
  fireEvent(element, event);
};
it("selects tasks, sums known partial amounts, and never calls unknown cost zero", () => {
  render(<CustomTaskStatistics zh rows={[row("complete", 2), row("partial", null, 3), row("unknown", null)]} periodLabel="近 7 天" />);
  expect(screen.queryByRole("region")).not.toBeInTheDocument();
  fireEvent.click(screen.getByRole("button", { name: /自定义统计/ }));
  fireEvent.click(screen.getByRole("checkbox", { name: /unknown/ }));
  const status = screen.getByRole("status");
  expect(status).toHaveTextContent("已选 1 项暂无估算");
  fireEvent.click(screen.getByRole("button", { name: "全选" }));
  expect(status).toHaveTextContent("已选 3 项$5.00");
  expect(status).toHaveTextContent("2 项成本不全");
  fireEvent.click(screen.getByRole("checkbox", { name: /complete/ }));
  expect(status).toHaveTextContent("已选 2 项$3.00");
  fireEvent.click(screen.getByRole("button", { name: "清空选择" }));
  expect(status).toHaveTextContent("已选 0 项$0.00");
  expect(within(screen.getByRole("region")).getAllByRole("checkbox").every(input => !(input as HTMLInputElement).checked)).toBe(true);
});
it("does not retain a removed task in totals and separates the same task on different devices", () => {
  const rows = [row('["mac","same"]', 2), row('["windows","same"]', 3)];
  const { rerender } = render(<CustomTaskStatistics zh rows={rows} periodLabel="今日" />);
  fireEvent.click(screen.getByRole("button", { name: /自定义统计/ }));
  fireEvent.click(screen.getByRole("button", { name: "全选" }));
  expect(screen.getByRole("status")).toHaveTextContent("已选 2 项$5.00");
  rerender(<CustomTaskStatistics zh rows={[rows[1]]} periodLabel="今日" />);
  expect(screen.getByRole("status")).toHaveTextContent("已选 1 项$3.00");
});
it("tears only after a deliberate drag, then copies selected tasks and reports clipboard failures", async () => {
  const copy = vi.mocked(copyCustomTaskCard);
  copy.mockResolvedValueOnce(undefined).mockRejectedValueOnce(new Error("clipboard denied"));
  render(<CustomTaskStatistics zh rows={[row("selected", 2), row("other", 3)]} periodLabel="近 7 天" />);
  fireEvent.click(screen.getByRole("button", { name: /自定义统计/ }));
  const button = screen.getByRole("button", { name: "打印账单 PNG" });
  expect(button).toBeDisabled();
  fireEvent.click(screen.getByRole("checkbox", { name: /selected/ }));
  fireEvent.click(button);
  expect(copy).not.toHaveBeenCalled();
  expect(screen.getByRole("group", { name: "账单打印机" })).toBeInTheDocument();
  await waitFor(() => expect(screen.getByRole("button", { name: "直接复制 PNG" })).toBeEnabled(), { timeout: 2000 });
  const paper = screen.getByRole("button", { name: "拖动账单撕下并复制 PNG" });
  pointer(paper, "pointerdown", 1, 100, 100);
  pointer(paper, "pointermove", 1, 125, 100);
  pointer(paper, "pointerup", 1, 125, 100);
  expect(copy).not.toHaveBeenCalled();
  expect(paper).toHaveStyle({ "--tear-x": "0px" });
  pointer(paper, "pointerdown", 2, 100, 100);
  pointer(paper, "pointermove", 2, 185, 115);
  expect(paper).toHaveStyle({ "--tear-x": "85px" });
  pointer(paper, "pointerup", 2, 185, 115);
  expect(copy).toHaveBeenCalledTimes(1);
  await waitFor(() => expect(screen.getByText("账单已放进剪贴板")).toBeInTheDocument());
  expect(copy).toHaveBeenCalledWith([expect.objectContaining({ id: "selected" })], "近 7 天", true);
  fireEvent.click(screen.getByRole("button", { name: "打印账单 PNG" }));
  await waitFor(() => expect(screen.getByRole("button", { name: "直接复制 PNG" })).toBeEnabled(), { timeout: 2000 });
  fireEvent.click(screen.getByRole("button", { name: "直接复制 PNG" }));
  await waitFor(() => expect(screen.getByRole("alert")).toHaveTextContent("clipboard denied"));
});
it("cancels a tear without copying and supports keyboard activation", async () => {
  const copy = vi.mocked(copyCustomTaskCard);
  copy.mockReset().mockResolvedValue(undefined);
  render(<CustomTaskStatistics zh rows={[row("selected", 2)]} periodLabel="今日" />);
  fireEvent.click(screen.getByRole("button", { name: /自定义统计/ }));
  fireEvent.click(screen.getByRole("checkbox", { name: /selected/ }));
  fireEvent.click(screen.getByRole("button", { name: "打印账单 PNG" }));
  const paper = await screen.findByRole("button", { name: "拖动账单撕下并复制 PNG" });
  await waitFor(() => expect(paper).toHaveAttribute("tabindex", "0"), { timeout: 2000 });
  pointer(paper, "pointerdown", 3, 50, 50, "touch");
  pointer(paper, "pointermove", 3, 50, 150, "touch");
  pointer(paper, "pointercancel", 3, 50, 150, "touch");
  expect(copy).not.toHaveBeenCalled();
  expect(paper).toHaveStyle({ "--tear-y": "0px" });
  fireEvent.keyDown(paper, { key: "Enter" });
  await waitFor(() => expect(copy).toHaveBeenCalledTimes(1));
});
